# Generated by Django 4.1.7 on 2023-03-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='student',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='health_care',
            new_name='healthCare',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lastname_patient',
            new_name='lastnamePatient',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name_patient',
            new_name='namePatient',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='nameEstudiante',
        ),
        migrations.AlterField(
            model_name='patient',
            name='datebirth',
            field=models.CharField(max_length=15),
        ),
    ]
