# Generated by Django 4.1.7 on 2023-03-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_student_patient_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTratamiento', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Patient',
            new_name='student',
        ),
    ]
